/* ============================================================
   The Reading Room — manatee-blog style SPA (zero build)
   Views:  #/ [#/p/<n>] home · #/blogs[ #/blogs#<name> ] · #/summaries[ #/summaries/<n> ] · #/post/<dir>
   data.js is regenerated by rebuild_site.py; everything else is static.
   ============================================================ */
(function () {
  'use strict';

  var DATA = window.READING_DATA || { meta: {}, counts: {}, posts: [], blogs: [] };
  var POSTS = DATA.posts || [];
  var BLOGS = DATA.blogs || [];
  var SITE_NAME = 'The Reading Room';
  var body = document.body;

  if (!POSTS.length) {
    body.innerHTML = '<div class="app-loading">data.js 为空 — 请先运行 rebuild_site.py</div>';
    return;
  }

  /* ---------------- text helpers ---------------- */

  function esc(s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  }
  function fmt(n) { return (Number(n) || 0).toLocaleString('en-US'); }
  function plainText(md) {
    if (!md) return '';
    return String(md)
      .replace(/```[\s\S]*?```/g, ' ')
      .replace(/!\[[^\]]*\]\([^)]*\)/g, ' ')
      .replace(/\[([^\]]+)\]\([^)]*\)/g, '$1')
      .replace(/^#{1,6}\s+/gm, '')
      .replace(/[*_`~>#|]/g, '')
      .replace(/\s+/g, '');
  }
  function defaultDoc(p) { return (p.docs && (p.docs.zh || p.docs.yuanwen)) || ''; }
  function charsOf(md) { return plainText(md).length; }
  function readMin(n) { return Math.max(1, Math.ceil((n || 0) / 600)); }

  var TOTAL_CHARS = POSTS.reduce(function (a, p) { return a + charsOf(defaultDoc(p)); }, 0);
  var POST_BY_DIR = {}; POSTS.forEach(function (p) { POST_BY_DIR[p.dir] = p; });

  /* ---------------- mini markdown ----------------
     Ported from the PKBase app.js renderer (verified on all 40 posts).
     Two adaptations for the manatee theme:
       - code fences wrapped in <div class="highlight"> (theme/highlight.css)
       - blockquote content wrapped in <p> (post.css styles blockquote p)
     Tables require a |---| separator row, as before. */

  function inline(s) {
    s = esc(s);
    s = s.replace(/!\[([^\]]*)\]\(([^)\s]+)[^)]*\)/g, function (_, alt, url) {
      return '<img src="' + url + '" alt="' + alt + '" loading="lazy">';
    });
    s = s.replace(/\[([^\]]+)\]\(([^)\s]+)(?:\s+&quot;[^&]*&quot;)?\)/g, function (_, tt, u) {
      var ext = /^https?:|^mailto:/.test(u) ? ' target="_blank" rel="noopener"' : '';
      return '<a href="' + u + '"' + ext + '>' + tt + '</a>';
    });
    s = s.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
    s = s.replace(/(^|[^*])\*([^*\n]+)\*/g, '$1<em>$2</em>');
    return s;
  }

  function splitRow(line) {
    return line.replace(/^\|/, '').replace(/\|$/, '').split('|').map(function (c) { return c.trim(); });
  }

  function mdToHtml(md, imgBase) {
    if (!md) return '';
    var src = String(md).replace(/\r\n?/g, '\n');
    if (imgBase) src = src.replace(/\(images\//g, '(' + imgBase + 'images/');
    var stash = [];
    function put(html) { stash.push(html); return '\u0000' + (stash.length - 1) + '\u0000'; }
    src = src.replace(/```[^\n]*\n([\s\S]*?)(?:```|$)/g, function (_, code) {
      return put('<div class="highlight"><pre><code>' + esc(code.replace(/\n$/, '')) + '</code></pre></div>');
    });
    var codes = [];
    src = src.replace(/`([^`\n]+)`/g, function (_, c) {
      codes.push('<code>' + esc(c) + '</code>');
      return '\u0000c' + (codes.length - 1) + '\u0000';
    });
    src = src.replace(/(^|[^(\[>"'=])(https?:\/\/[^\s<()\[\]]+)/g, function (_, pre, url) {
      var m2 = url.match(/^(.*?)[.,;:!?]+$/);
      var clean = m2 ? m2[1] : url;
      var tail = m2 ? url.slice(clean.length) : '';
      return pre + '[' + clean + '](' + clean + ')' + tail;
    });
    var lines = src.split('\n');
    var out = [], i = 0;
    while (i < lines.length) {
      var tt = lines[i].trim();
      if (tt === '') { i++; continue; }
      if (/^\u0000c?\d+\u0000$/.test(tt)) { out.push(tt); i++; continue; }
      var h = tt.match(/^(#{1,6})\s+(.*)$/);
      if (h) { out.push('<h' + h[1].length + '>' + inline(h[2]) + '</h' + h[1].length + '>'); i++; continue; }
      if (/^(-{3,}|\*{3,})$/.test(tt)) { out.push('<hr>'); i++; continue; }
      if (/^>/.test(tt)) {
        var q = [];
        while (i < lines.length && /^>/.test(lines[i].trim())) { q.push(lines[i].trim().replace(/^>\s?/, '')); i++; }
        out.push('<blockquote><p>' + inline(q.join(' ')) + '</p></blockquote>');
        continue;
      }
      if (/^\|/.test(tt) && i + 1 < lines.length && /^\|[\s:|-]+\|$/.test(lines[i + 1].trim())) {
        var head = splitRow(tt); i += 2;
        var rows = [];
        while (i < lines.length && /^\|/.test(lines[i].trim())) { rows.push(splitRow(lines[i].trim())); i++; }
        out.push('<div class="table-wrap"><table><thead><tr>' + head.map(function (c) { return '<th>' + inline(c) + '</th>'; }).join('') +
          '</tr></thead><tbody>' +
          rows.map(function (r) { return '<tr>' + r.map(function (c) { return '<td>' + inline(c) + '</td>'; }).join('') + '</tr>'; }).join('') +
          '</tbody></table></div>');
        continue;
      }
      if (/^([-*]|\d+\.)\s+/.test(tt)) {
        var ordered = /^\d+\./.test(tt);
        var items = [];
        while (i < lines.length && /^([-*]|\d+\.)\s+/.test(lines[i].trim())) {
          items.push(lines[i].trim().replace(/^([-*]|\d+\.)\s+/, ''));
          i++;
        }
        out.push((ordered ? '<ol>' : '<ul>') + items.map(function (x) { return '<li>' + inline(x) + '</li>'; }).join('') + (ordered ? '</ol>' : '</ul>'));
        continue;
      }
      var par = [tt]; i++;
      while (i < lines.length) {
        var n = lines[i].trim();
        if (n === '' || /^(#{1,6}\s|>|\||[-*]\s|\d+\.\s)/.test(n) || /^(-{3,}|\*{3,})$/.test(n) || /^\u0000c?\d+\u0000$/.test(n)) break;
        par.push(n); i++;
      }
      out.push('<p>' + par.map(inline).join('<br>') + '</p>');
    }
    return out.join('\n')
      .replace(/\u0000c(\d+)\u0000/g, function (_, n) { return codes[+n]; })
      .replace(/\u0000(\d+)\u0000/g, function (_, n) { return stash[+n]; });
  }

  /* ---------------- shared chrome ---------------- */

  var SEARCH_OVERLAY = ''
    + '<div class="search-overlay" data-search-overlay data-search-index-url="search-index.json" data-tags-url="#/blogs" hidden>'
    + '<div class="search-overlay-inner">'
    + '<div class="topbar search-topbar">'
    + '<button id="search-back-button" class="topbar-button search-back-button" type="button" aria-label="返回">'
    + '<svg t="1772968619879" class="search-back-icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="5778" aria-hidden="true">'
    + '<path d="M588.501333 119.786667l-362.026666 362.026666a42.666667 42.666667 0 0 0 0 60.373334l362.026666 362.026666a42.666667 42.666667 0 0 0 60.352-60.352L316.992 512 648.853333 180.138667a42.666667 42.666667 0 0 0-60.352-60.352z" fill="currentColor" p-id="5779"></path>'
    + '</svg></button>'
    + '<form class="search-inline-form" role="search"><div class="search-input-area">'
    + '<input id="search-input" class="search-input" type="search" name="q" placeholder="Happy hacking..." autocomplete="off" spellcheck="false" aria-label="搜索文章">'
    + '</div></form></div>'
    + '<div id="search-status" class="char-total-counter search-status" aria-live="polite"></div>'
    + '<ul id="search-results" class="search-results" aria-live="polite"></ul>'
    + '</div></div>';

  function topbar() {
    var btn = function (href, label) { return '<div class="topbar-button"><a href="' + href + '">' + label + '</a></div>'; };
    return '<div class="topbar">'
      + '<div class="topbar-row topbar-row-secondary">'
      + btn('#/', 'Home') + btn('#/blogs', 'Blogs') + btn('#/summaries', 'Summaries')
      + '<div class="topbar-button"><button class="search-trigger" type="button" data-search-trigger>Search</button></div>'
      + '</div></div>';
  }

  function navigatebar() {
    var btn = function (href, label) { return '<div class="navigatebar-button"><a href="' + href + '">' + label + '</a></div>'; };
    return '<div class="navigatebar">'
      + '<div class="navigatebar-row navigatebar-row-secondary">'
      + btn('#/', 'Home') + btn('#/blogs', 'Blogs') + btn('#/summaries', 'Summaries')
      + '<div class="navigatebar-button"><button class="search-trigger" type="button" data-search-trigger>Search</button></div>'
      + '</div></div>';
  }

  function siteTitle() {
    return '<div class="slogan"><a href="#/">' + SITE_NAME + '</a></div>';
  }

  var PER_PAGE = 10;

  function pageOf(s) {
    var n = parseInt(s, 10);
    return (isFinite(n) && n >= 1) ? n : 1;
  }

  function clampPage(page, total) {
    var pages = Math.max(1, Math.ceil(total / PER_PAGE));
    return Math.min(Math.max(1, page), pages);
  }

  function pagerHtml(page, total, hrefOf) {
    var pages = Math.ceil(total / PER_PAGE);
    if (pages <= 1) return '';
    var nums = [];
    for (var i = 1; i <= pages; i++) {
      if (i === 1 || i === pages || Math.abs(i - page) <= 1) nums.push(i);
      else if (nums[nums.length - 1] !== -1) nums.push(-1);
    }
    var html = '<div class="pager">';
    html += page > 1
      ? '<a class="pager-btn" href="' + hrefOf(page - 1) + '">← 上一页</a>'
      : '<span class="pager-btn off">← 上一页</span>';
    nums.forEach(function (n) {
      if (n === -1) { html += '<span class="pager-ellipsis">…</span>'; return; }
      html += n === page
        ? '<span class="pager-num cur">' + n + '</span>'
        : '<a class="pager-num" href="' + hrefOf(n) + '">' + n + '</a>';
    });
    html += page < pages
      ? '<a class="pager-btn" href="' + hrefOf(page + 1) + '">下一页 →</a>'
      : '<span class="pager-btn off">下一页 →</span>';
    return html + '</div>';
  }

  /* ---------------- views ---------------- */

  function postLine(p) {
    var href = '#/post/' + encodeURIComponent(p.dir);
    // prose summary (curated in post_meta.json); fall back to the 总结.md
    // one-liner, then to the raw text head (last resort only)
    var sum = p.summary || p.oneliner || '';
    if (!sum) {
      var t = plainText(p.docs && p.docs.yuanwen);
      sum = t.length > 80 ? t.slice(0, 80) + ' ...' : t;
    }
    if (sum.length > 80) { sum = sum.slice(0, 80) + ' ...'; }
    // tag pills: author (links to the blog filter) + topic pills, then
    // "|"-separated special group: Source Link (second last), then the
    // source-type pills (Substack / Podcast) saying where it was published
    var SOURCE_TAGS = { Substack: 1, Podcast: 1 };
    var tags = '';
    var author = (p.tags && p.tags.length) ? p.tags[0] : p.blog;
    if (author) {
      if (p.blog) {
        tags += '<a class="category-link" href="#/blogs#' + encodeURIComponent(p.blog) + '"><div class="category">' + esc(author) + '</div></a>';
      } else {
        tags += '<div class="category">' + esc(author) + '</div>';
      }
    }
    var sources = '';
    for (var i = 1; i < (p.tags ? p.tags.length : 0); i++) {
      if (SOURCE_TAGS[p.tags[i]]) {
        sources += '<div class="category">' + esc(p.tags[i]) + '</div>';
      } else {
        tags += '<div class="category">' + esc(p.tags[i]) + '</div>';
      }
    }
    if (p.url) {
      tags += '<div class="tag-group"><div class="tag-sep">|</div>'
        + '<a class="category-link" href="' + esc(p.url) + '" target="_blank" rel="noopener"><div class="category">Source Link</div></a></div>';
    }
    if (sources) {
      tags += '<div class="tag-group"><div class="tag-sep">|</div>' + sources + '</div>';
    }
    return '<li class="post-line">'
      + '<a class="post-title" href="' + href + '">' + esc(p.title) + '</a>'
      + '<a href="' + href + '"><div class="post-summary">' + esc(sum) + '</div></a>'
      + '<div class="post-info">'
      + '<div class="category-area">' + tags + '</div>'
      + '<div class="right-info-area"><div class="char-counter">' + fmt(charsOf(defaultDoc(p))) + '字</div><div class="post-date">' + esc(p.date) + '</div></div>'
      + '</div></li>';
  }

  function homeHtml(page) {
    page = clampPage(page, POSTS.length);
    var start = (page - 1) * PER_PAGE;
    var slice = POSTS.slice(start, start + PER_PAGE);
    return '<div class="content">'
      + topbar()
      + siteTitle()
      + '<ul>'
      + '<div class="char-total-counter">' + POSTS.length + '篇文章 ' + fmt(TOTAL_CHARS) + '字</div>'
      + slice.map(postLine).join('')
      + '</ul>'
      + pagerHtml(page, POSTS.length, function (n) { return n === 1 ? '#/' : '#/p/' + n; })
      + '</div>'
      + SEARCH_OVERLAY;
  }

  function blogsSorted() {
    return BLOGS.slice().sort(function (a, b) { return b.count - a.count || a.name.localeCompare(b.name); });
  }

  function blogsHtml(name) {
    var all = blogsSorted();
    var shown = name ? all.filter(function (b) { return b.name === name; }) : all;
    var groups = shown.map(function (b) {
      var items = POSTS.filter(function (p) { return p.blog === b.name; }).map(function (p) {
        return '<article class="archive-item"><a href="#/post/' + encodeURIComponent(p.dir) + '">'
          + esc(p.title) + '<span class="archive-date">' + esc(p.date) + '</span></a></article>';
      }).join('');
      return '<div class="archive-group"><a name="' + esc(b.name) + '"></a>'
        + '<div class="category-head">「' + esc(b.name) + '」</div>' + items + '</div>';
    }).join('');
    var cats = all.map(function (b) {
      return '<a class="category-item" href="#/blogs#' + encodeURIComponent(b.name) + '">'
        + '<div class="category-name">' + esc(b.name) + '</div>'
        + '<div class="category-number">[' + b.count + ']</div></a>';
    }).join('');
    return navigatebar()
      + '<div class="tag-box">'
      + (name ? '<a class="blog-back" href="#/blogs">← 全部博客</a>' : '')
      + '<div id="archives">' + groups + '</div>'
      + '<div class="categories-area"><div class="categories-area-title">[Blogs]</div>' + cats + '</div>'
      + '</div>'
      + SEARCH_OVERLAY;
  }

  function summariesHtml(page) {
    var withSum = POSTS.filter(function (p) { return p.hasSum && p.docs && p.docs.summary; });
    page = clampPage(page, withSum.length);
    var start = (page - 1) * PER_PAGE;
    var slice = withSum.slice(start, start + PER_PAGE);
    var items = slice.map(function (p) {
      return '<article class="archive-item"><a href="#/post/' + encodeURIComponent(p.dir) + '">'
        + esc(p.title) + '<span class="archive-date">' + esc(p.date) + '</span></a></article>';
    }).join('');
    return navigatebar()
      + '<div class="tag-box">'
      + '<div id="archives">'
      + '<div class="char-total-counter">' + withSum.length + '篇总结</div>'
      + items
      + '</div>'
      + pagerHtml(page, withSum.length, function (n) { return n === 1 ? '#/summaries' : '#/summaries/' + n; })
      + '</div>'
      + SEARCH_OVERLAY;
  }

  function stripDocHeader(md, p) {
    // Strip the leading doc header: the H1 title (原文/中文版/总结) and a
    // directly-glued H2 subtitle; attribute lines (来源/标题/发布日期/
    // 原文链接/说明/链接/主题/整理日期/博客/博客名/翻译整理日期/抓取日期/
    // 关于本文的说明, optionally with an English "/Source"-style suffix;
    // plain, "- " bulleted or "> " quoted, key optionally **bold**); the
    // "本文件为…/关于本文的说明" translator note (quoted continuation
    // lines); one closing "---" separator; and - in Substack captures -
    // the title block after the hero image: H1/H2 lines repeating the
    // post title or blog name, plus the image glued right before one.
    // The post page header already shows title/date/source/原文链接.
    var lines = md.split('\n');
    var n = lines.length;
    var i = 0;
    while (i < n && lines[i].trim() === '') i++;
    var removed = false;
    if (i < n && /^#\s+/.test(lines[i].trim())) {
      i++; removed = true;
      if (i < n && /^##\s+/.test(lines[i].trim())) i++; // glued subtitle
    }
    var metaKey = function (t) {
      t = t.replace(/^>\s*/, '');
      t = t.replace(/^[-*]\s+/, '');
      t = t.replace(/^\*\*(.+?)\*\*\s*[:：]/, '$1:');
      var m = /^(来源|标题|发布日期|原文链接|说明|链接|主题|整理日期|博客|博客名|翻译整理日期|抓取日期|关于本文的说明)(\s*\/\s*[A-Za-z]+)?\s*[:：]/.exec(t);
      return m ? m[1] : null;
    };
    var lat = function (s) { return String(s).toLowerCase().replace(/[^a-z0-9]/g, ''); };
    // The Substack captures repeat the page title block mid-document:
    // hero image, "# BlogName", logo image, "# PostTitle", subtitle.
    // Anchor on the blog name (parenthetical author dropped); the title
    // block then consumes at most one more H1/H2 plus one H2/H3.
    var blogCore = p ? lat(String(p.blog || '').replace(/[（(][^）)]*[）)]/g, '')) : '';
    var titleCore = p ? lat(p.title || '') : '';
    var isAnchor = function (t) {
      if (!/^#{1,2}\s+/.test(t)) return false;
      var hl = lat(t.replace(/^#{1,2}\s+/, ''));
      if (blogCore.length >= 10 && hl.indexOf(blogCore) !== -1) return true;
      if (titleCore.length >= 10 && hl.indexOf(titleCore) !== -1) return true;
      return false;
    };
    var inNote = false;
    while (i < n) {
      var t = lines[i].trim();
      if (t === '') { inNote = false; i++; continue; }
      var k = metaKey(t);
      if (k) {
        i++; removed = true;
        if (k === '关于本文的说明') inNote = true; // multi-line quoted note
        continue;
      }
      if (/^(>)?\s*本文件为/.test(t)) { i++; removed = true; inNote = true; continue; }
      if (inNote && /^>/.test(t)) { i++; continue; }
      if (t === '---' && removed) { i++; continue; }
      if (removed && isAnchor(t)) {
        i++; // blog-name heading (or title heading) starts the title block
        var phase = 2;
        while (i < n) {
          var u = lines[i].trim();
          if (u === '' || u === '---') { i++; continue; }
          if (phase === 2) {
            if (/^!/.test(u)) { i++; continue; } // logo/hero image
            var hm = u.match(/^(#{1,2})\s/);
            if (hm) { i++; phase = 3; continue; } // the post title
          } else {
            if (/^#{2,3}\s/.test(u)) { i++; break; } // the subtitle, then stop
          }
          break;
        }
        continue;
      }
      if (removed && /^!\[/.test(t)) {
        // drop the hero image only when the title block follows it
        var j = i + 1;
        while (j < n && lines[j].trim() === '') j++;
        if (j < n && isAnchor(lines[j].trim())) { i++; continue; }
      }
      break;
    }
    while (i < n && lines[i].trim() === '') i++;
    return lines.slice(i).join('\n');
  }

  function postBody(p, tab) {
    var doc = stripDocHeader((p.docs && p.docs[tab]) || '', p);
    var brief = p.summary || p.oneliner || '';
    // 简要 is rendered as a plain blockquote above the body.
    return brief ? '> ' + brief.replace(/\n+/g, '\n> ') + '\n\n' + doc : doc;
  }

  function postHtml(p, tab) {
    var doc = postBody(p, tab);
    var n = charsOf(doc);
    function tabBtn(t, label) {
      if (t !== 'yuanwen' && !(p.docs && p.docs[t])) return '';
      return '<span class="doc-tab' + (t === tab ? ' active' : '') + '" data-tab="' + t + '">' + label + '</span>';
    }
    return navigatebar()
      + '<div class="post-layout">'
      + '<div class="content-area">'
      + '<div class="title">' + esc(p.title) + '</div>'
      + '<div class="category-area">「<a href="#/blogs#' + encodeURIComponent(p.blog) + '"><div class="category">' + esc(p.blog) + '</div></a>」</div>'
      + '<div class="post-meta">'
      + '<span class="post-meta-item">' + esc(p.date) + '</span>'
      + '<span class="post-meta-item" id="meta-chars">' + fmt(n) + '字</span>'
      + '<span class="post-meta-item post-meta-reading-time" id="meta-reading">预计阅读' + readMin(n) + '分钟</span>'
      + (p.url ? '<a class="post-meta-item" href="' + esc(p.url) + '" target="_blank" rel="noopener">原文链接</a>' : '')
      + '</div>'
      + '<div class="doc-tabs">' + tabBtn('yuanwen', '原文') + tabBtn('zh', '中文版') + tabBtn('summary', '总结') + '</div>'
      + '<div class="content" id="doc-content">' + mdToHtml(doc, '../substack/' + p.dir + '/') + '</div>'
      + '</div>'
      + '</div>'
      + SEARCH_OVERLAY;
  }

  /* ---------------- photoswipe lightbox ----------------
     Same logic as scripts/photoswipe-init.js, re-runnable per render. */

  var APPLE_CLOSE_SVG = '\n<svg aria-hidden="true" class="pswp__icn" viewBox="0 0 24 24" width="24" height="24">\n  <path d="M6 6L18 18M18 6L6 18"/>\n</svg>';
  var APPLE_ZOOM_SVG = '\n<svg aria-hidden="true" class="pswp__icn" viewBox="0 0 24 24" width="24" height="24">\n  <path class="pswp__zoom-icn-bar-h" d="M4.5 12H19.5"></path>\n  <path class="pswp__zoom-icn-bar-v" d="M12 4.5V19.5"></path>\n</svg>';
  var APPLE_ARROW_PREV_SVG = '\n<svg aria-hidden="true" class="pswp__icn" viewBox="0 0 24 24" width="24" height="24">\n  <path d="M15 6L9 12L15 18"></path>\n</svg>';
  var APPLE_ARROW_NEXT_SVG = '\n<svg aria-hidden="true" class="pswp__icn" viewBox="0 0 24 24" width="24" height="24">\n  <path d="M9 6L15 12L9 18"></path>\n</svg>';
  var APPLE_OPEN_ORIGINAL_SVG = '\n<svg aria-hidden="true" class="pswp__icn" viewBox="0 0 24 24" width="24" height="24">\n  <path d="M14 4H20V10"></path>\n  <path d="M20 4L10 14"></path>\n  <path d="M20 14V18C20 19.1 19.1 20 18 20H6C4.9 20 4 19.1 4 18V6C4 4.9 4.9 4 6 4H10"></path>\n</svg>';

  function isSkippableImage(img) {
    return Boolean(img.closest('pre, code, .highlighter-rouge'));
  }

  function getImageSize(img) {
    var w = Number.parseInt(img.getAttribute('width') || '', 10);
    var hgt = Number.parseInt(img.getAttribute('height') || '', 10);
    if (Number.isFinite(w) && w > 0 && Number.isFinite(hgt) && hgt > 0) return { width: w, height: hgt };
    if (img.naturalWidth > 0 && img.naturalHeight > 0) return { width: img.naturalWidth, height: img.naturalHeight };
    return { width: 1600, height: 1200 };
  }

  function ensureAnchor(img) {
    var existing = img.closest('a.post-image-link');
    if (existing) return existing;
    var anchor = document.createElement('a');
    anchor.className = 'post-image-link';
    anchor.href = img.currentSrc || img.src;
    img.parentNode.insertBefore(anchor, img);
    anchor.appendChild(img);
    return anchor;
  }

  function ensureAnchorMetadata(anchor) {
    var img = anchor.querySelector('img');
    if (!img) return;
    var imageSrc = img.currentSrc || img.getAttribute('src') || '';
    var imageSrcset = img.getAttribute('srcset') || '';
    var imageSizes = img.getAttribute('sizes') || '100vw';
    var existingHref = anchor.getAttribute('href') || '';
    var existingOriginal = anchor.getAttribute('data-original-src') || '';
    var imgOriginal = img.dataset.originalSrc || '';
    var originalSrc = existingOriginal || imgOriginal || existingHref || imageSrc;
    if (!existingOriginal && originalSrc) anchor.setAttribute('data-original-src', originalSrc);
    if (!existingHref || (existingHref === originalSrc && imageSrc && imageSrc !== originalSrc)) {
      anchor.setAttribute('href', imageSrc || originalSrc);
    }
    if (!anchor.getAttribute('data-pswp-src')) anchor.setAttribute('data-pswp-src', anchor.getAttribute('href') || imageSrc || originalSrc);
    if (!anchor.getAttribute('data-pswp-srcset') && imageSrcset) anchor.setAttribute('data-pswp-srcset', imageSrcset);
    if (!anchor.getAttribute('data-pswp-sizes')) anchor.setAttribute('data-pswp-sizes', imageSizes);
    var size = getImageSize(img);
    anchor.setAttribute('data-pswp-width', String(size.width));
    anchor.setAttribute('data-pswp-height', String(size.height));
  }

  function bootstrapGallery() {
    var anchors = [];
    var images = Array.prototype.slice.call(document.querySelectorAll('.content img'));
    for (var i = 0; i < images.length; i++) {
      var img = images[i];
      if (isSkippableImage(img)) continue;
      var anchor = ensureAnchor(img);
      ensureAnchorMetadata(anchor);
      anchors.push(anchor);
      if (!img.complete) {
        img.addEventListener('load', function () { ensureAnchorMetadata(anchor); }, { once: true });
      }
    }
    return anchors;
  }

  function getCurrentOriginalUrl(pswp) {
    var slide = pswp && pswp.currSlide;
    if (!slide || !slide.data) return '';
    var el = slide.data.element;
    return (el && el.getAttribute('data-original-src'))
      || (el && el.dataset && el.dataset.originalSrc)
      || slide.data.originalSrc || slide.data.src || '';
  }

  var LightboxClass = null;
  var currentLb = null;
  function ensureLightboxClass() {
    if (LightboxClass) return Promise.resolve(LightboxClass);
    return import('https://cdn.jsdelivr.net/npm/photoswipe@5.4.4/dist/photoswipe-lightbox.esm.min.js')
      .then(function (m) { LightboxClass = m.default || null; return LightboxClass; })
      .catch(function () { LightboxClass = null; return null; });
  }

  function initLightbox(seq) {
    var anchors = bootstrapGallery();
    if (currentLb) { try { currentLb.destroy(); } catch (e) {} currentLb = null; }
    if (!anchors.length) return;
    ensureLightboxClass().then(function (cls) {
      if (seq !== renderSeq) return;
      if (!cls) {
        anchors.forEach(function (a) { a.target = '_blank'; a.rel = 'noopener'; });
        return;
      }
      currentLb = new cls({
        gallery: '.content',
        children: 'a.post-image-link',
        preload: [0, 1],
        closeSVG: APPLE_CLOSE_SVG,
        zoomSVG: APPLE_ZOOM_SVG,
        arrowPrevSVG: APPLE_ARROW_PREV_SVG,
        arrowNextSVG: APPLE_ARROW_NEXT_SVG,
        pswpModule: function () { return import('https://cdn.jsdelivr.net/npm/photoswipe@5.4.4/dist/photoswipe.esm.min.js'); }
      });
      currentLb.on('uiRegister', function () {
        currentLb.pswp.ui.registerElement({
          name: 'open-original',
          order: 15,
          isButton: true,
          title: 'View original image',
          ariaLabel: 'View original image in new tab',
          html: APPLE_OPEN_ORIGINAL_SVG,
          onClick: function (_event, _el, pswp) {
            var u = getCurrentOriginalUrl(pswp);
            if (u) window.open(u, '_blank', 'noopener,noreferrer');
          }
        });
      });
      currentLb.init();
    });
  }

  /* ---------------- page style pairs ----------------
     home / post / tags pairs are swapped through the two <link> slots
     in index.html. The new pair is appended after app.css (so its rules
     win the cascade during the overlap) and the previously active pair
     is removed once the new one is in. */

  var PAIRS = {
    home: ['styles/home.css', 'styles/home_mobile.css'],
    post: ['styles/post.css', 'styles/post_mobile.css'],
    tags: ['styles/tags.css', 'styles/tags_mobile.css']
  };
  var curPair = 'home';
  var prevPairEls = null; // the pair currently in <head> after the first swap

  function applyPair(kind) {
    var pair = PAIRS[kind] || PAIRS.home;
    var nd = document.createElement('link');
    nd.rel = 'stylesheet'; nd.media = 'screen and (min-width: 600px)';
    var nm = document.createElement('link');
    nm.rel = 'stylesheet'; nm.media = 'screen and (max-width: 600px)';
    // Keep the pair BEFORE app.css in the cascade: app.css must win ties.
    var anchor = document.querySelector('link[href="app.css"]');
    if (anchor) {
      anchor.parentNode.insertBefore(nd, anchor);
      anchor.parentNode.insertBefore(nm, anchor);
    } else {
      document.head.appendChild(nd); document.head.appendChild(nm);
    }
    nd.href = pair[0]; nm.href = pair[1];
    var od = document.getElementById('page-style-desktop'); if (od) od.remove();
    var om = document.getElementById('page-style-mobile'); if (om) om.remove();
    if (prevPairEls) { prevPairEls.d.remove(); prevPairEls.m.remove(); }
    prevPairEls = { d: nd, m: nm };
    curPair = kind;
  }

  function ensurePair(kind, cb) {
    if (kind === curPair) { cb(); return; }
    var pair = PAIRS[kind] || PAIRS.home;
    // Do NOT wait for the <link> load events: a link whose media query does
    // not match the viewport is fetched lazily (or never), so its load event
    // never fires and the view render would deadlock. Pull the pair through
    // fetch() instead — it always settles — then append the links (which hit
    // the cache) and only then drop the old pair.
    if (typeof fetch === 'function' && location.protocol !== 'file:') {
      Promise.all([fetch(pair[0], { cache: 'force-cache' }),
                   fetch(pair[1], { cache: 'force-cache' })])
        .then(function () { applyPair(kind); cb(); },
              function () { applyPair(kind); cb(); });
    } else {
      applyPair(kind); cb();
    }
  }

  /* ---------------- enhancement scripts ----------------
     Fetched once, re-executed after every render (self-contained IIFEs
     that bind to whatever DOM is present at execution time). */

  var peSrc = null, searchSrc = null;
  function runPe() {
    if (!peSrc) return;
    try { new Function(peSrc)(); } catch (e) { console.warn('post-enhancements failed:', e); }
  }
  function runSearch() {
    if (!searchSrc) return;
    try { new Function(searchSrc)(); } catch (e) { console.warn('search failed:', e); }
  }

  /* ---------------- render + router ---------------- */

  var renderSeq = 0;

  function render(html, bodyClass, kind, after) {
    var seq = ++renderSeq;
    ensurePair(kind, function () {
      if (seq !== renderSeq) return;
      body.className = bodyClass || '';
      body.innerHTML = html;
      window.scrollTo(0, 0);
      if (after) after(seq);
      runSearch();
    });
  }

  function afterPost(seq) {
    runPe();
    initLightbox(seq);
  }

  function switchTab(tab) {
    var m = (location.hash || '').match(/^#\/post\/(.+)$/);
    if (!m) return;
    var p = POST_BY_DIR[decodeURIComponent(m[1])];
    if (!p || !p.docs || !p.docs[tab]) return;
    var seq = renderSeq;
    document.querySelectorAll('.doc-tab').forEach(function (t) {
      t.classList.toggle('active', t.getAttribute('data-tab') === tab);
    });
    var cc = document.getElementById('doc-content');
    if (!cc) return;
    var doc = postBody(p, tab);
    cc.innerHTML = mdToHtml(doc, '../substack/' + p.dir + '/');
    var n = charsOf(doc);
    var mc = document.getElementById('meta-chars'); if (mc) mc.textContent = fmt(n) + '字';
    var mr = document.getElementById('meta-reading'); if (mr) mr.textContent = '预计阅读' + readMin(n) + '分钟';
    runPe();
    initLightbox(seq);
    window.scrollTo(0, 0);
  }

  function route() {
    var h = location.hash || '#/';
    var rest = h.slice(1);
    if (rest.charAt(0) !== '/') {
      var el = document.getElementById(decodeURIComponent(rest));
      if (el) el.scrollIntoView({ behavior: 'smooth' });
      return;
    }
    var parts = rest.slice(1).split('#');
    var segs = parts[0].split('/').filter(Boolean);
    var view = segs[0] || 'home';
    if (view === 'home' || view === 'p') {
      document.title = SITE_NAME;
      render(homeHtml(pageOf(view === 'p' ? segs[1] : '')), '', 'home');
    } else if (view === 'blogs') {
      var name = parts[1] ? decodeURIComponent(parts[1]) : '';
      if (name && !BLOGS.some(function (b) { return b.name === name; })) name = '';
      document.title = SITE_NAME + ' · Blogs';
      render(blogsHtml(name || null), '', 'tags');
    } else if (view === 'summaries') {
      document.title = SITE_NAME + ' · Summaries';
      render(summariesHtml(pageOf(segs[1] || '')), '', 'tags');
    } else if (view === 'post') {
      var dir = decodeURIComponent(segs.slice(1).join('/'));
      var p = POST_BY_DIR[dir];
      if (!p) {
        document.title = SITE_NAME;
        render(homeHtml(), '', 'home');
        return;
      }
      var tab = (p.docs && p.docs.zh) ? 'zh' : 'yuanwen';
      document.title = SITE_NAME + ' · ' + p.title;
      render(postHtml(p, tab), 'post-page', 'post', afterPost);
    } else {
      document.title = SITE_NAME;
      render(homeHtml(), '', 'home');
    }
  }

  document.addEventListener('click', function (e) {
    var t = e.target && e.target.closest ? e.target.closest('.doc-tab') : null;
    if (t) { switchTab(t.getAttribute('data-tab')); return; }
    var a = e.target && e.target.closest ? e.target.closest('a') : null;
    if (!a) return;
    var href = a.getAttribute('href') || '';
    if (href.charAt(0) === '#' && href.charAt(1) !== '/') {
      var el = document.getElementById(decodeURIComponent(href.slice(1)));
      if (el) { e.preventDefault(); el.scrollIntoView({ behavior: 'smooth', block: 'start' }); }
    }
  });

  window.addEventListener('hashchange', route);

  Promise.all([
    fetch('scripts/post-enhancements.js', { cache: 'no-cache' }).then(function (r) { return r.text(); }).catch(function () { return null; }),
    fetch('scripts/search.js', { cache: 'no-cache' }).then(function (r) { return r.text(); }).catch(function () { return null; })
  ]).then(function (res) {
    peSrc = res[0];
    searchSrc = res[1];
    route();
  });
})();
